title: HaoChen Lu's Homepage
page-top-title: HaoChen Lu
top-section-bg-text: Be what you wanna be
home-subtitle: HaoChen Lu&ensp;|&ensp;陆昊辰
copyright-text: '&copy; HaoChen Lu 2025. All Rights Reserved.'
  